# Use Ubuntu as the base image
FROM ubuntu:latest

# Update and install dependencies
RUN apt-get update && apt-get install -y \
    curl \
    wget \
    build-essential \
    cmake \
    libeigen3-dev \
    libgl1-mesa-dev \
    && rm -rf /var/lib/apt/lists/*

    # Install VTK from source
WORKDIR /tmp
RUN wget https://www.vtk.org/files/release/9.3/VTK-9.3.0.tar.gz \
    && tar xf VTK-9.3.0.tar.gz \
    && cd VTK-9.3.0 \
    && mkdir build \
    && cd build \
    && cmake .. \
    && make -j$(nproc) \
    && make install \
    && cd /tmp \
    && rm -rf VTK-9.3.0 VTK-9.3.0.tar.gz

WORKDIR /app

COPY . /app


CMD ["bash", "./build_process.sh"]



